
# hint to run:
# ansible-playbook playbook.yml -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -u vagrant


- name: setup wordpress and utilities
  hosts: all
  sudo: True

  roles:
    - server
    - php
    - mysql
    - wordpress

